/**
 * planExport.js — pure text/data formatting for the Plan screen's print &
 * share feature (REMEDI_MASTER_PLAN.md §1.9 — "print it and takes it to the
 * store"). No DOM, no window/navigator here — src/api/browser.js is the only
 * file allowed to touch `window.print`/`navigator.share`/clipboard; this
 * module only turns a WeeklyPlan (src/state/dailyPlan.js) into the plain
 * strings/structures those calls (and MealQueueScreen's print view) consume.
 *
 * Guardrails (frozen, per the T4C task brief):
 *  - FOODS only, never calories. Calorie context is plan-creation-time-only
 *    (see calorieNeeds.js's header comment) and is never printed or shared.
 *  - No health claims beyond the one factual footer line below — keep it
 *    exactly as written, don't expand it.
 *  - Never fabricate: an empty slot is OMITTED, never invented as "—" or
 *    padded with a placeholder. A falsy/empty condition-name list omits the
 *    "for: …" clause entirely rather than claim an unknown condition set.
 */

import { PLAN_SLOTS } from './config.js';
import { nextSevenDays } from '../screens/plan/planDates.js';

/** The one allowed disclaimer-ish line — neutral and factual, never expanded. */
export const PRINT_FOOTER_LINE = 'Generated by Remedi — not medical advice';

/**
 * Label + short date for one plan day, e.g. `{ label: 'Today', dateLabel:
 * 'Aug 10' }`. Reuses `nextSevenDays()`'s Today/Tomorrow/weekday logic (the
 * one source of truth for "what day is this, relative to today" — already
 * used by the Plan screen's day strip) for any date key still inside the
 * current rolling window. A date key OUTSIDE that window (a stale day that
 * hasn't rolled out of the plan's `days` map yet — see planBuilder.js's
 * rolling-window doc, or simply a caller passing an arbitrary plan) falls
 * back to a plain weekday/date computed directly from the key itself,
 * rather than silently dropping the day from the export.
 * @param {string} dateKey - LOCAL 'YYYY-MM-DD'
 * @returns {{ label: string, dateLabel: string }}
 */
function dayMeta(dateKey) {
  const found = nextSevenDays().find((d) => d.key === dateKey);
  if (found) return { label: found.label, dateLabel: found.sublabel };

  const [y, m, d] = String(dateKey).split('-').map(Number);
  const date = new Date(y, (m || 1) - 1, d || 1);
  return {
    label: date.toLocaleDateString('en-US', { weekday: 'long' }),
    dateLabel: date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
  };
}

/**
 * "Aug 10" (single day) or "Aug 10 – Aug 16" (range) from a plan's sorted
 * day keys. Empty input yields `''`.
 * @param {string[]} sortedDayKeys
 * @returns {string}
 */
function formatRangeLabel(sortedDayKeys) {
  if (sortedDayKeys.length === 0) return '';
  const first = dayMeta(sortedDayKeys[0]).dateLabel;
  const last = dayMeta(sortedDayKeys[sortedDayKeys.length - 1]).dateLabel;
  return first === last ? first : `${first} – ${last}`;
}

/**
 * Non-empty, de-fabricated display names for a slot's items. Drops any
 * item missing a real string `name` rather than let `undefined`/`null`
 * leak into joined text — tolerates a slot key that's entirely absent from
 * `day.slots` (pre-Beverages-restore legacy days; see config.js `PLAN_SLOTS`
 * doc) since the caller passes `day?.slots?.[key]`, which is `undefined`.
 * @param {Array<{name?: string}>|undefined} items
 * @returns {string[]}
 */
function slotItemNames(items) {
  return (items || [])
    .map((item) => item?.name)
    .filter((name) => typeof name === 'string' && name.length > 0);
}

/**
 * Condition names filtered of any falsy/non-string entry — never let a
 * stray null/undefined slip into a joined "for: …" clause.
 * @param {string[]|undefined} conditionNames
 * @returns {string[]}
 */
function cleanConditionNames(conditionNames) {
  return (conditionNames || []).filter((name) => typeof name === 'string' && name.length > 0);
}

/**
 * The header line shared by both exports below: "Remedi meal plan · <range>
 * · for: <names>" — either trailing clause is OMITTED (never fabricated)
 * when there's nothing honest to put there.
 * @param {string} rangeLabel
 * @param {string[]} cleanNames
 * @returns {string}
 */
function headerLine(rangeLabel, cleanNames) {
  const parts = ['Remedi meal plan'];
  if (rangeLabel) parts.push(rangeLabel);
  if (cleanNames.length > 0) parts.push(`for: ${cleanNames.join(', ')}`);
  return parts.join(' · ');
}

/**
 * Plain-text week summary — suitable for both `navigator.share`'s `text`
 * field and a raw clipboard paste (see src/api/browser.js `share()`).
 * Lists FOODS only, never calories (see this module's header). Every
 * non-empty slot becomes one line ("Breakfast: item, item"); empty slots
 * are skipped entirely — never rendered as "Breakfast: —" or padded with a
 * placeholder. A day with nothing planned in ANY slot gets an honest
 * "Nothing planned" line instead of silently vanishing from the summary.
 * @param {import('../state/dailyPlan.js').WeeklyPlan|null} plan
 * @param {{ conditionNames?: string[] }} [opts]
 * @returns {string} '' if `plan` is null or has no days.
 */
export function formatWeekPlanText(plan, { conditionNames = [] } = {}) {
  if (!plan || !plan.days || typeof plan.days !== 'object') return '';
  const dayKeys = Object.keys(plan.days).sort();
  if (dayKeys.length === 0) return '';

  const cleanNames = cleanConditionNames(conditionNames);
  const lines = [headerLine(formatRangeLabel(dayKeys), cleanNames), ''];

  for (const dateKey of dayKeys) {
    const day = plan.days[dateKey];
    const { label, dateLabel } = dayMeta(dateKey);
    lines.push(`${label} · ${dateLabel}`);

    let wroteSlot = false;
    for (const slot of PLAN_SLOTS) {
      const names = slotItemNames(day?.slots?.[slot.key]);
      if (names.length === 0) continue;
      wroteSlot = true;
      lines.push(`${slot.label}: ${names.join(', ')}`);
    }
    if (!wroteSlot) lines.push('Nothing planned');
    lines.push('');
  }

  lines.push(PRINT_FOOTER_LINE);
  return lines.join('\n');
}

/**
 * Structured week model for the print view (MealQueueScreen's
 * `.plan-print-view`) — the same underlying data as `formatWeekPlanText`,
 * shaped for JSX mapping instead of string lines. Empty slots are omitted
 * from a day's `slots` array (same honesty rule as the text export); a day
 * with nothing planned at all still appears with an empty `slots` array, so
 * the print view can render an explicit "Nothing planned" note instead of
 * silently dropping the day.
 * @param {import('../state/dailyPlan.js').WeeklyPlan|null} plan
 * @param {{ conditionNames?: string[] }} [opts]
 * @returns {{
 *   rangeLabel: string,
 *   conditionLine: string,
 *   days: Array<{ label: string, dateLabel: string, slots: Array<{ label: string, items: string[] }> }>
 * } | null} `null` only when `plan` itself is null/has no `days` object.
 */
export function buildPrintModel(plan, { conditionNames = [] } = {}) {
  if (!plan || !plan.days || typeof plan.days !== 'object') return null;
  const dayKeys = Object.keys(plan.days).sort();
  const cleanNames = cleanConditionNames(conditionNames);

  return {
    rangeLabel: formatRangeLabel(dayKeys),
    conditionLine: cleanNames.length > 0 ? `For: ${cleanNames.join(', ')}` : '',
    days: dayKeys.map((dateKey) => {
      const day = plan.days[dateKey];
      const { label, dateLabel } = dayMeta(dateKey);
      const slots = PLAN_SLOTS
        .map((slot) => ({ label: slot.label, items: slotItemNames(day?.slots?.[slot.key]) }))
        .filter((s) => s.items.length > 0);
      return { label, dateLabel, slots };
    }),
  };
}
